name: Deploy to VPS

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

      - name: Deploy to VPS
        env:
          VPS_USER: root  
          VPS_HOST: 45.88.105.79 
          REMOTE_PATH: /root/backend-app  # Replace with your project path on VPS
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd $REMOTE_PATH
            git pull origin main  # Pull the latest code
            # Add commands here, e.g., npm install, npm run build, etc.
          EOF